### ISSUE TITLE
使用模型报错

### ISSUE THREAD

**Issue by tangbh** [initial-h/AlphaZero_Gomoku_MPI#11]
使用 tensorflow 1.14.0 ,tensorlayer 1.8.5 运行 python human_play.py 出现错误：

2019-09-25 16:45:35.017514: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:                      184 : Not found: Key model/conv2d_1/W_conv2d not found in checkpoint
Traceback (most recent call last):
  File "/app/tangbh/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 135                      6, in _do_call
    return fn(*args)
  File "/app/tangbh/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 134                      1, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/app/tangbh/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 142                      9, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key model/conv2d_1/W_conv2d not found in checkpoint
         [[{{node save/RestoreV2}}]]
  (1) Not found: Key model/conv2d_1/W_conv2d not found in checkpoint
         [[{{node save/RestoreV2}}]]
         [[save/RestoreV2/_675]]
0 successful operations.
0 derived errors ignored.

使用自己训练的模型不会出错，是不是版本问题？

**Comment by initial-h** [comment]
时间有点久远，不太记得之前的版本了。
我测试了一下我目前的环境版本，tensorflow 1.12.0 ,tensorlayer 1.10.1，可以成功运行。

**Comment by tangbh** [comment]
谢谢，用您的版本可以用了。

**Comment by tangbh** [comment]
很厉害，根本下不过它

**Comment by tangbh** [comment]
我自己训练的模型用不了，看来tensorflow的兼容性真差.

**Comment by initial-h** [comment]
估计是存取模型的地方有一点变化，导致layer名称对应不上了。
